version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: file_monitoring
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: